import test from 'node:test';
import assert from 'node:assert/strict';
import { prepareJournal, journalHeader, exportJournalPacket, parseJournalPacket, decryptJournalPacket, JOURNAL_TEXT_BYTES, IPSEITY_JOURNAL_MODULE_KEY, IPSEITY_JOURNAL_STATE_SCHEMA } from '../../web/modules/journal.mjs';
import { MEMORY_KDF_ROUNDS, memorySeal } from '../../web/memory/crypto.mjs';
const address = byte => '0x' + byte.repeat(20);
const identity = { chainId: '31337', collection: address('11'), tokenId: '8', account: address('22'), registry: address('33'), owner: address('44'), epoch: '2' };
const passphrase = 'a unique test-only journal phrase';
const text = '  Private journal: violet-bird 7291 — 🫧\nPreserve this whitespace.  \n';

test('public publication preserves the raw text and enforces the UTF-8 bound', async () => {
  const result = await prepareJournal({ mode: 'public', text });
  assert.equal(result.chainText, text);
  assert.equal(result.byteLength, new TextEncoder().encode(text).length);
  assert.deepEqual(Object.keys(result).sort(), ['byteLength', 'chainText', 'mode']);
  assert.equal((await prepareJournal({ mode: 'public', text: 'é'.repeat(JOURNAL_TEXT_BYTES / 2) })).byteLength, JOURNAL_TEXT_BYTES);
  for (const input of [' ', 'é'.repeat(1501), '\ud800']) await assert.rejects(prepareJournal({ mode: 'public', text: input }), /UTF-8|Unicode/);
  await assert.rejects(prepareJournal({ mode: 'unspecified', text }), /Choose public or encrypted/);
});

test('encrypted transaction bytes contain no plaintext/passphrase and canonical export recovers exact text', async () => {
  const result = await prepareJournal({ mode: 'encrypted', text, passphrase, identity });
  assert.equal(result.packet.payload.rounds, MEMORY_KDF_ROUNDS);
  assert.equal(result.packet.payload.cipher, 'AES-256-GCM');
  assert.equal(result.chainText, exportJournalPacket(result.packet));
  assert.deepEqual(parseJournalPacket(result.chainText), result.packet);
  assert.ok(result.byteLength < 32768);
  assert.equal(JSON.stringify(result).includes('violet-bird'), false);
  assert.equal(JSON.stringify(result).includes(passphrase), false);
  assert.equal(JSON.stringify(result).includes('thesis'), false);
  assert.deepEqual(result.packet.header, journalHeader(identity));
  const opened = await decryptJournalPacket(result.chainText, passphrase, { expectedIdentity: identity });
  assert.equal(opened.text, text);
  assert.deepEqual(opened.header, result.packet.header);
});

test('wrong passphrase, authenticated header changes and ciphertext damage fail closed', async () => {
  const result = await prepareJournal({ mode: 'encrypted', text, passphrase, identity });
  await assert.rejects(decryptJournalPacket(result.packet, 'a different wrong test phrase'), /wrong passphrase, changed header, or damaged ciphertext/);
  const changedHeader = JSON.parse(result.chainText); changedHeader.header.owner = address('55');
  await assert.rejects(decryptJournalPacket(exportJournalPacket(changedHeader), passphrase), /changed header/);
  const damaged = JSON.parse(result.chainText); damaged.payload.data = (damaged.payload.data[0] === '0' ? '1' : '0') + damaged.payload.data.slice(1);
  await assert.rejects(decryptJournalPacket(exportJournalPacket(damaged), passphrase), /damaged ciphertext/);
  await assert.rejects(decryptJournalPacket(result.packet, passphrase, { expectedIdentity: { ...identity, epoch: '3' } }), /different NFT or custody epoch/);
  const plaintext = JSON.parse(result.chainText); plaintext.payload = { mode: 'public', body: { thesis: text } };
  assert.throws(() => parseJournalPacket(plaintext), /encrypted journal packet/);
  assert.equal((await decryptJournalPacket(result.packet, passphrase)).text, text);
});

test('maximum text recovers exactly through the existing padded memory format', async () => {
  const original = ' '.repeat(998) + 'é'.repeat(1000) + '\n\n';
  assert.equal(new TextEncoder().encode(original).length, JOURNAL_TEXT_BYTES);
  const result = await prepareJournal({ mode: 'encrypted', text: original, passphrase, identity });
  assert.ok(result.byteLength <= 16384);
  assert.equal((await decryptJournalPacket(result.chainText, passphrase)).text, original);
  assert.throws(() => parseJournalPacket(JSON.stringify(result.packet, null, 2)), /canonical export/);
});

// Frozen packet generated by the unmodified MASTER implementation from commit
// 84961c3f0f0112760d900668f3df490ed4b3d9be, using test-only text/passphrase.
const originalPacket = "{\"header\":{\"account\":\"0x2222222222222222222222222222222222222222\",\"chainId\":\"31337\",\"collection\":\"0x1111111111111111111111111111111111111111\",\"epoch\":\"2\",\"owner\":\"0x4444444444444444444444444444444444444444\",\"registry\":\"0x3333333333333333333333333333333333333333\",\"schema\":\"anima.module-journal-header/1\",\"textEncoding\":\"utf8-base64/1\",\"tokenId\":\"8\"},\"payload\":{\"cipher\":\"AES-256-GCM\",\"data\":\"7fcb573a38452658120689a4666224ff7bcc000126a4d80ad1a88861f1e563efb1dea54606580eda24e4080f6f24af6c155b0f1d2df080e6ed4d23d0ce9bff4d59a915678878ae5b15b122b993b2d3d9414c8c5d537d167c39583f8aa88f7cea3e8ed522cab3c8d22caa216d6be458394062367a0a318b0d3dd6241b1b4bd783f2bf4e457fc2da94d804c73ae40e1e4ce8b9f959ecedd4a570733dab44cca4c7b82f78647291ce81e1d9d9f79216801b0a0e42cc5b62fbe913fc7ddcac4ed04d37ede3b1858063913298fad8297e519087118f27d42505b07284657da2cc8ff0d9e2f2b345b575457ee8a842b12bb03358099c90fe3c8796c7f2e1f7720cc1cd69839dbe0e07d9fb6424693f411de9a17ced2917f4f903ac43418feca288a623889c6a1ae07526c33502289ecbcd9c31dc0757735980f5a1f58abcac165d6d085cf007514440f1a119afac6e082a17e41f7fdeecbf7c3aaab688a825e9056f551f1398ed7ca85e9d569122b12d1453edd037511224a5399d15b489ce530af47ae94fae5eb79a7ac5365988d16d92ed2975959f69bf35ba20e7d3a45aed02a7b088937cc7c54cf842a73576ae0382ef732268c7a2d7809e9426f3a4596fdfe1f11cefd2cd5c7251fa89ef77593390e7ac8b503cac2d0809283cff187a9aa79606a0469290a3d5c9ddf5501b0dcfc8ca0a1ee857df193cf62418a9ce50589a15fd4f512b45a0aa9af5ab974383320e5a52909c6ef1635cf0ecf390c8ebf4b66d6302e99d447d705c6b1e0a6fedf4e438db275e9b2e3bb1ae493d64bf257b986e9c36b322ae9c0065132fee270963e574cae278b49018e5780de4ca6cb27d9bfc935dd422c06dd36b9cd1bae655533362cb86ceccde0458d703e571c88e64e12ad49385f5d35c27c92f331ef11a7c2a070209bbe1ed6f244f8dcf3d3e3bd27fbe202ee97601e69aa392a1a1b104f46e9045497dda140ce66184727282f959e15f9742eb55539586b759e9a36e1502bcadfd34bbbd1417c7acc4bd01730c61ac42ae16d7ab8438baeeb04c906d7644b358b1b510340cc43b3096a43fd3fef7c1e70c20f90595dab0fb684e0a7b0ea653c2b7b32ea817e12c688c1ddafc066c4350fd4a8fdab7c7c3f597669d4d6e4418e0daa6fd4d1ecccdfe688dba295a6b9503ba5de0eadfb4bdead0e7783094cda8b7d3dbfd1ffbe063ab2ac30432f1f19481a5e16373f145df20b86314f94d3bb649e7d2ede5a2d17c46e83463698e6ea844590b907741f40ec37035700b551cef67247e8eb2e6161096d96f2aa8d55e8856527789d739b78faf2b846d78ad08bb40b16145ca878299d4e48858a89a47378b4382b05a478e71894a9b191f86a248947126db4c788385f77dcbdf10070a72d84dc676dc2b397fb6b0760a08f9765a64a3f69ca6f7e03e62b1266fbd335d9486a8302701e45e5df264cc038a658e51de54\",\"iv\":\"de022978840d00a7890281bd\",\"kdf\":\"PBKDF2-SHA256\",\"mode\":\"encrypted\",\"rounds\":600000,\"salt\":\"d752e5991ee00aa51647721174942c94\"},\"schema\":\"anima.encrypted-journal-packet/1\"}";
test('the original ANIMA packet and memory seal remain byte compatible', async () => {
  const packet = parseJournalPacket(originalPacket);
  assert.equal(exportJournalPacket(packet), originalPacket);
  const opened = await decryptJournalPacket(originalPacket, 'original packet compatibility phrase', { expectedIdentity: identity });
  assert.equal(opened.text, '  Compatible ANIMA → IPSEITY — 🫧\n');
  assert.equal(memorySeal(packet.header, packet.payload).digest, '0x8808644f8678d8b7a701034b7be28c79eb03722cd1d8565ea20ae1ae8abd5c6d');
});

test('IPSEITY journal storage uses dedicated, stable module and state identifiers', () => {
  assert.equal(IPSEITY_JOURNAL_MODULE_KEY, '0xc5aea30c2508a889428d301e9d9764424fd7c6d894ad485152543211ad12ed8b');
  assert.equal(IPSEITY_JOURNAL_STATE_SCHEMA, '0x6490e32caaa9859f20331de202810060de9045dd48a05f213890cf4a30338ab9');
});
