// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import {Etch} from "./Etch.sol";
import {LibNum} from "./lib/LibNum.sol";

/// Fixed application bytes live apart from the immutable public archive.
/// No holder-supplied byte is evaluated as HTML, CSS or JavaScript.
contract DeskEtch {
    using LibNum for uint256;
    Etch public immutable ETCH;
    address public immutable HUB;
    constructor(Etch etch) { ETCH = etch; HUB = address(etch.HUB()); }
    function _sel(string memory sig) private pure returns (string memory) {
        bytes memory h = bytes(LibNum.hex32(keccak256(bytes(sig))));
        bytes memory out = new bytes(10);
        for (uint256 i; i < 10; ++i) out[i] = h[i];
        return string(out);
    }
    function config(uint256 id) external view returns (string memory) {
        return string.concat("<script>var ETCH_CONFIG={id:'", id.str(), "',chain:'", block.chainid.str(),
            "',etch:'", LibNum.hexAddr(address(ETCH)), "',hub:'", LibNum.hexAddr(address(HUB)),
            "',inscribe:'", _sel("inscribe(uint256,uint8,bytes)"), "',admits:'", _sel("admits(uint8,bytes)"),
            "',addressFor:'", _sel("addressFor(bytes)"), "',owner:'", _sel("ownerOf(uint256)"), "'};</script>");
    }
    function head() external pure returns (string memory) {
        return "<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>IPSEITY / What it remembers</title><style>"
        "*{box-sizing:border-box}body{margin:0;background:#060c18;color:#d9e8f2;font:15px/1.65 system-ui,sans-serif}body:before{content:'';position:fixed;z-index:-1;width:75vw;height:75vw;left:30vw;top:-42vw;border:1px solid #1d668055;border-radius:50%;box-shadow:0 0 140px #166b9726,inset 0 0 160px #148fc820;pointer-events:none}header{display:flex;justify-content:space-between;align-items:center;padding:28px 6vw;border-bottom:1px solid #bddbff18;font-size:11px;letter-spacing:.2em}header a{font-size:18px;letter-spacing:.28em;color:#eef9ff;text-decoration:none}main{max-width:1180px;margin:68px auto;padding:0 30px}.eyebrow{font-size:11px;letter-spacing:.17em;color:#84c9e1}h1{font:clamp(40px,6vw,76px)/1.1 Georgia,serif;font-weight:400;letter-spacing:-.035em;margin:20px 0}h2{font:30px Georgia,serif;margin-top:0}h3{font-size:17px;font-weight:500;margin:12px 0}h3 span{font-size:12px;color:#8195aa}.lead{color:#9aafc3;max-width:580px;font-size:18px}.summary{display:flex;gap:24px;flex-wrap:wrap;padding:24px 0;margin:30px 0 44px;border-block:1px solid #bddbff18}.hash{font:11px/1.7 ui-monospace,monospace;overflow-wrap:anywhere;color:#859caf}.summary strong{font-weight:500}.layout{display:grid;grid-template-columns:1fr 1fr;gap:70px}label{display:block;font-size:12px;margin:20px 0 7px;color:#abc3d5}input,select,textarea,button{font:inherit}textarea,select,input{width:100%;color:#d7e6ef;background:#0b1727;border:1px solid #2b4258;border-radius:4px;padding:12px}textarea{resize:vertical;min-height:180px}button{margin:15px 8px 0 0;padding:11px 20px;background:#a4dceb;color:#091520;border:0;border-radius:4px;cursor:pointer}button:disabled{opacity:.45;cursor:wait}button.secondary{background:#152e42;color:#d9e8f2}button:focus-visible,a:focus-visible,textarea:focus-visible,select:focus-visible,input:focus-visible{outline:2px solid #b9ecff;outline-offset:3px}.muted,footer{font-size:12px;color:#859caf}article{border-top:1px solid #bddbff24;padding:20px 0 26px}a{color:#aadceb;text-underline-offset:5px}#review{padding:20px;background:#102334;margin-top:24px;border:1px solid #356075}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}#status{white-space:pre-wrap;overflow-wrap:anywhere}footer{margin-top:70px;padding-top:24px;border-top:1px solid #bddbff18}@media(max-width:760px){main{margin-top:40px;padding:0 22px}.layout{grid-template-columns:1fr;gap:45px}header span{font-size:9px}header{padding:22px}}</style></head><body>";
    }
    function client() external pure returns (string memory) {
        return "<script>(function(){'use strict';var C=ETCH_CONFIG,$=function(id){return document.getElementById(id)},pending=null,revision=0,busy=false;"
        "function status(t){$('status').textContent=t}function clear(){revision++;pending=null;$('review').hidden=true}function word(x){return BigInt(x).toString(16).padStart(64,'0')}function tail(hex){return word(hex.length/2)+hex.padEnd(Math.ceil(hex.length/64)*64,'0')}function call(to,data,from){return window.ethereum.request({method:'eth_call',params:[{to:to,data:data,from:from},'latest']})}"
        "async function identity(request){var p=window.ethereum;if(!p)throw Error('Open this page in a wallet-enabled browser.');var chain=await p.request({method:'eth_chainId'});if(BigInt(chain)!==BigInt(C.chain))throw Error('Switch your wallet to chain '+C.chain+'.');var accounts=await p.request({method:request?'eth_requestAccounts':'eth_accounts'});if(!accounts.length)throw Error('Connect the current owner wallet.');var from=accounts[0];var owner=await call(C.hub,C.owner+word(C.id),from);if(!/^0x[0-9a-fA-F]{64}$/.test(owner)||('0x'+owner.slice(-40)).toLowerCase()!==from.toLowerCase())throw Error('Only the current token owner can write here.');return from}"
        "function lock(v){busy=v;$('preview').disabled=v;$('send').disabled=v}['words','kind','file'].forEach(function(id){$(id).addEventListener('input',clear)});$('cancel').onclick=clear;"
        "if(window.ethereum&&window.ethereum.on){['accountsChanged','chainChanged','disconnect'].forEach(function(e){window.ethereum.on(e,function(){clear();status('Wallet changed. Preview again before confirming.')})})}"
        "$('preview').onclick=async function(){if(busy)return;clear();lock(true);var rev=revision;try{var from=await identity(true),kind=$('kind').value,bytes;if(kind==='3'){if(!$('file').files.length)throw Error('Choose the data file to inscribe.');if($('file').files[0].size>24575)throw Error('The data file exceeds 24,575 bytes.');bytes=new Uint8Array(await $('file').files[0].arrayBuffer())}else{bytes=new TextEncoder().encode($('words').value)}if(!bytes.length)throw Error('Write a memory or select a file first.');if(bytes.length>24575)throw Error('This inscription is too large.');var hex=Array.from(bytes,function(b){return b.toString(16).padStart(2,'0')}).join('');var admission=await call(C.etch,C.admits+word(kind)+word(64)+tail(hex),from);if(!/^0x[0-9a-fA-F]{128}$/.test(admission))throw Error('The archive returned an invalid validation response.');if(BigInt('0x'+admission.slice(2,66))!==1n)throw Error('Format refused by the archive (reason '+BigInt('0x'+admission.slice(66,130)).toString()+'). Change the text or use a data file.');var data=C.inscribe+word(C.id)+word(kind)+word(96)+tail(hex);await call(C.etch,data,from);var address=await call(C.etch,C.addressFor+word(32)+tail(hex),from);if(!/^0x[0-9a-fA-F]{128}$/.test(address))throw Error('The archive returned an invalid content address.');if(rev!==revision)throw Error('The form or wallet changed. Preview again.');pending={from:from,data:data,rev:rev,provider:window.ethereum};$('details').textContent='Token '+C.id+' on chain '+C.chain+'\\n'+bytes.length+' bytes / format '+kind+'\\nAuthor '+from+'\\nArchive '+C.etch+'\\nContent address 0x'+address.slice(26,66)+'\\nNative value 0; network gas applies.\\nThese bytes are public and cannot be erased.';$('review').hidden=false;status('Simulation succeeded. Review the details, then confirm in your wallet.')}catch(e){clear();status(e.message||String(e))}finally{lock(false)}};"
        "$('send').onclick=async function(){if(busy||!pending)return;lock(true);var tx=pending;try{var from=await identity(false);if(!pending||tx.provider!==window.ethereum||tx.rev!==revision||from.toLowerCase()!==tx.from.toLowerCase())throw Error('Wallet or form changed. Preview again.');await call(C.etch,tx.data,from);var chain=await window.ethereum.request({method:'eth_chainId'}),accounts=await window.ethereum.request({method:'eth_accounts'});if(!pending||tx.provider!==window.ethereum||tx.rev!==revision||BigInt(chain)!==BigInt(C.chain)||!accounts.length||accounts[0].toLowerCase()!==from.toLowerCase())throw Error('Wallet changed. Preview again.');var hash=await window.ethereum.request({method:'eth_sendTransaction',params:[{from:from,to:C.etch,data:tx.data,value:'0x0',chainId:'0x'+BigInt(C.chain).toString(16)}]});clear();status('Submitted: '+hash+'\\nSubmission is not confirmation. Check the receipt in your wallet, then reload the archive.')}catch(e){clear();status(e.message||String(e))}finally{lock(false)}}})();</script>";
    }
}
